### ISSUE TITLE
Factor out the argv parsing logic

### ISSUE THREAD

**Issue by lupino3** [EduMIPS64/edumips64#199]
MainCLI currently depends on Main (eek) for command-line arguments parsing, which is itself intertwined with setting properties of the Main class.

This means the build of the CLI jar depends on the Swing sub-package, which is not great.

**Comment by lupino3** [comment]
It would be nice to use a library like picocli: https://picocli.info/

**Comment by iwodder** [comment]
@lupino3 if you still need/want this done, I'd be happy to pick it up. Using picocli seems straightforward.

**Comment by lupino3** [comment]
Yes please @iwodder! Thanks a lot.

**Comment by iwodder** [comment]
@lupino3 you're welcome. I should be able to get something up in the next few days. Any preferences on the picocli version? I was going to use their latest which is 4.5.0.

**Comment by lupino3** [comment]
The latest stable version would be perfect. Thanks!

**Comment by lupino3** [comment]
This was fixed by @iwodder in #448. Thanks!
