### ISSUE TITLE
Make the CLI more usable

### ISSUE THREAD

**Issue by lupino3** [EduMIPS64/edumips64#264]
The CLI was always intended as an experimental program to test the EduMIPS64 features from a command line.

Turns out some people used it. It might be worth at some point adding a few more features to make it more usable. Here is an initial list of things to do:

- [x] add a command to open a file (currently you MUST use `-f` or you cannot do anything useful with the simulator;
- [x] add a non-interactive mode, where the code just runs. Bonus points for allowing useful actions in this non-interactive mode, such as "dump memory at the end", "dump registers", "dump specific register", "dump specific memory location", "dump Dinero tracefile";
- [x] add Dinero tracefile output command;
- [x] add internationalization;
- [x] add options to visualize the configuration;
- [x] ~~allow to edit the configuration (this is potentially a very large work item compared to the others, not sure it is worth doing it);~~ (not worth doing unless someone asks for it)
- [x] #853
- [x] ~~release the JAR~~. (not needed, it's the same JAR)

**Comment by iwodder** [comment]
@lupino3 I know you're busy this week, but I can take this on. It would be possible to make some really usable with picocli. We could leverage that library since it is being used in the extraction of parseargs.

**Comment by lupino3** [comment]
Thank you very much @iwodder ! Sorry for not replying on the other issue yet. Yes please! 👍

**Comment by iwodder** [comment]
@lupino3 perfect, I am on it. Won't have something out until next week, I am busy this weekend.

**Comment by lupino3** [comment]
Closing this issue, as the main remaining item is only documentation, and I moved it to #853
