### ISSUE TITLE
Create Windows installer

### ISSUE THREAD

**Issue by lupino3** [EduMIPS64/edumips64#302]
There's a StackOverflow question on how to start EduMIPS64 in Windows: https://stackoverflow.com/questions/60990995/how-can-i-open-edumips-jar/61039766#61039766

For people not familiar with JAR files, this may not be super-intuitive.

We should explore the possibility of creating an installer for Windows, ideally bundling a JDK with it and building the `exe` (or `msi`) from CI.

**Comment by lupino3** [comment]
From a cursory look, launch4j seems promising: http://launch4j.sourceforge.net/

**Comment by lupino3** [comment]
There are some examples here on how to use a Gradle task to generate an executable with bundled JDK: https://github.com/TheBoegl/gradle-launch4j/issues/86

**Comment by lupino3** [comment]
I can't really find motivation to finish this task, I'll probably work on it if enough people request an installer / Windows binary.

**Comment by rocas777** [comment]
Hey there, I was able to make an executable with launch4J. Can make it work with the exe file and a folder with the jre. Since the exe refers to the jre with a relative path,you can make a release with only those two files. Then pack it with NSIS and give it away to Windows Users.

**Comment by lupino3** [comment]
Thanks @rocas777! That sounds like what we need!

Just one small thing: the point of the Windows installer would be to offer a "single click" installation experience, so I'd like to bundle the JRE within the installer.

Could you please make that change before sending the PR with the launch4j config?

Thanks for your help!

**Comment by lupino3** [comment]
Another alternative might be to use the tooling available in JDK 14+: https://openjdk.java.net/jeps/343
