### ISSUE TITLE
Issues with v1.2.7 packages

### ISSUE THREAD

**Issue by pviotti** [EduMIPS64/edumips64#311]
There are some packaging issues with the freshly released v1.2.7:
 - the slim jar does not contain the docs folder (which is required to get the help manual)
 - images, resources and compiled class files are copied twice in the jar (open one of the jar files to see this)

I think I've fixed this, I'll submit a PR.

**Comment by pviotti** [comment]
@lupino3 please let me know when you've replaced the fixed jars for v1.2.7. Thanks

**Comment by lupino3** [comment]
I'll try today; but there are 2 issues:
1) I'd bumped up the version to 1.2.8, so I'd have to revert that
2) I found a minor bug (a SEVERE logging statement for `div.d.s` which should not be emitted) which I fixed, but that should have tripped unit tests and I don't understand why

So I might skip fixing 1.2.7 and go with 1.2.7.1 as a minor bugfix release. Depending on the time available, I'll try to do it today.

If you want to fix the JARs for 1.2.7, feel free to do it, you should have the permissions to do so!

**Comment by pviotti** [comment]
I don't have permission to edit releases. Anyway, if there's a 1.2.7.1 or 1.2.8 upcoming, I won't release 1.2.7 for Arch, it's fine, as you prefer.

**Comment by lupino3** [comment]
You should have permissions now, but yes I plan to release shortly a 1.2.7.1 once I find some time to chase and fix that minor bug. Thanks!

**Comment by pviotti** [comment]
![image](https://user-images.githubusercontent.com/1350095/79115818-c7d1fb00-7d7e-11ea-9f9f-8d81bcbf64c2.png)
:laughing:
ack, I'll replace the binaries for 1.2.7.

**Comment by pviotti** [comment]
ok, I've replaced the two jars in v1.2.7. The code is the one at tag `v1.2.7` plus the cherry-picked commit of the fix ( https://github.com/EduMIPS64/edumips64/commit/65424f44131b5766722debab4d094bcdabe8d763 ).

**Comment by lupino3** [comment]
Thanks! I just published `v1.2.7.1`.
