### ISSUE TITLE
Set up a dependency upgrader bot

### ISSUE THREAD

**Issue by lupino3** [EduMIPS64/edumips64#314]
As per @pviotti's suggestion, we should set up a bot to keep dependencies updated.

We have dependencies both in the Gradle build file `build.gradle.kts` and in the documentation's `requirements.txt` (Python dependencies).

**Comment by lupino3** [comment]
Tried to set up dependabot, unfortunately it does not support Gradle Kotlin build files :(

**Comment by lupino3** [comment]
Trying to see if there is a way to store dependencies in a separate file (https://github.com/dependabot/feedback/issues/345)

**Comment by lupino3** [comment]
Same for Snyk, successor to Greenkeeper, it supports Kotlin only from the CLI and not via the github integration: https://support.snyk.io/hc/en-us/articles/360000911957-Language-support

**Comment by pviotti** [comment]
This one should work with Kotlin too: https://docs.renovatebot.com/java/
Here is the bot (I cannot add it): https://github.com/marketplace/renovate

**Comment by lupino3** [comment]
Thanks, I have enabled it! We should receive an onboarding PR soon, I guess: https://docs.renovatebot.com/configure-renovate/

**Comment by lupino3** [comment]
The PR is there and it detected both Java and Python, awesome! Thanks @pviotti

**Comment by lupino3** [comment]
@pviotti feel free to merge PRs if you see them incoming and they look good to you! Thanks for finding this nice service!
