### ISSUE TITLE
Memory windows : adding float/double value

### ISSUE THREAD

**Issue by tgrandpierre** [EduMIPS64/edumips64#618]
Hi,
It is a great tool for teaching !
Would it be possible to add the possibility to display decimal value of  floating point  memory content when clicking on a memory address  (as it is done for integer) ?
Thank you,
Thierry

**Comment by lupino3** [comment]
Hi @tgrandpierre,
sure, I will add the feature as soon as I have some time!

Thanks for taking the time to write down your feature request! :)

**Comment by tgrandpierre** [comment]
Great, many thanks !

**Comment by lupino3** [comment]
By the way, the feature is already there!
![image](https://user-images.githubusercontent.com/200139/133940709-b1e7a429-192d-40bc-acb2-3af3e934c170.png)
Choose `Configure > Settings > Appearance` and then uncheck the `Long/double mem. cells view`. That will show them as double values.

Let me know if it works for you. If that's what you were looking for, I'll iinstead work on improving its usability and documentation.

**Comment by tgrandpierre** [comment]
Yes, that make easier to verify/understand the memory contents !
Thank you !
