### ISSUE TITLE
Some floating-point division cycles missing in Cycles window

### ISSUE THREAD

**Issue by jcarletta** [EduMIPS64/edumips64#646]
[FP division execution cycles missing in cycles window.txt](https://github.com/EduMIPS64/edumips64/files/8149329/FP.division.execution.cycles.missing.in.cycles.window.txt)

![image](https://user-images.githubusercontent.com/63207457/155897428-6ff6ff9e-f420-4beb-9fbb-e44cdb946948.png)

When this code is run in EduMIPS64 v.1.2.9, the cycles window does not show the pipeline stages for the second division after the D09 stage.  

At one point when running this, I got this message in the terminal (but didn't get the message consistently):

org.edumips64.utils.CycleElement isFinalStateValid
SEVERE: D09 is not a valid final state.
Feb 27, 2022 2:28:31 PM org.edumips64.ui.swing.CPUSwingWorker haltCPU
SEVERE: Invalid CycleElement for instruction div.d f4,f3,f4

This is a problem with the CyclesUI and not the simulator itself; the floating-point division does execute and produce results.

**Comment by lupino3** [comment]
Thanks for reporting @jcarletta, this is fixed in #650, which I am merging now.

I have added your sample to the code as a regression test, I hope this is ok with you!

**Comment by lupino3** [comment]
I hope to release 1.2.10 after I merge the fixes for those 2 bugs you and your students recently reported (or re-reported in the case of #304).

**Comment by jcarletta** [comment]
Thank you for this release!  I appreciate the work!
