### ISSUE TITLE
DMULU instruction incompatible with WinMips64

### ISSUE THREAD

**Issue by smallg0at** [EduMIPS64/edumips64#779]
DMULU appears to be implemented as an alias of DMULTU, but the two instructions are actually different.

[WinMips64 Source Code](https://github.com/AndoniZubimendi/WinMIPS64/blob/d1fd07fb4655d2d7d6b47f38f038210a50af301a/src/pipeline.cpp#L63) shows that this instruction actually have 3 register inputs.

It can be tested by loading up factorial.s in WinMips64 examples, which will throw an "invalid register" error.

**Comment by lupino3** [comment]
https://s3-eu-west-1.amazonaws.com/downloads-mips/documents/MD00083-2B-MIPS64INT-AFP-06.01.pdf the MIPS64 ISA confirms that they are two different instructions and should not be aliased. Thanks for the bug report!

**Comment by lupino3** [comment]
Note that if we fix this bug it's worth changing the minor version to 3, as we'd be changing the behavior of one of the instructions (even if the behavior was incorrect).
