### ISSUE TITLE
readrthedocs build failing

### ISSUE THREAD

**Issue by lupino3** [EduMIPS64/edumips64#788]
https://readthedocs.org/projects/edumips64/builds/21993443/

Seems to use an old Python version (3.7), which is unsupported by our Sphinx version.

**Comment by lupino3** [comment]
This makes the new Simplified Chinese docs added by @smallg0at not available on readthedocs.

**Comment by smallg0at** [comment]
Seems changing the version of readthedocs's python is possible.

https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by lupino3** [comment]
@smallg0at your change fixed the build, thanks: https://readthedocs.org/projects/edumips64/builds/22048174/.

Unfortunately, it's not picking up the chinese docs: https://edumips64.readthedocs.io/en/latest/

**Comment by lupino3** [comment]
I might need to add some configs in the buildthedocs admin panel, hang on
