### ISSUE TITLE
readthedocs build does not pick up the Chinese docs

### ISSUE THREAD

**Issue by lupino3** [EduMIPS64/edumips64#792]
I added a Simplified Chinese project in readthedocs, but it still picks up the english config file. Need to understand how to point it to the right `conf.py` file.

zn build: https://readthedocs.org/projects/edumips64-zn/builds/22060446/
it build: https://readthedocs.org/projects/edumips64-it/builds/22048175/

**Comment by smallg0at** [comment]
`zn` is not the right language tag. Please use `zh` instead.

**Comment by lupino3** [comment]
I changed the project name (even if the project ID still says `zn`), but the language is actually set in the admin page:

![image](https://github.com/EduMIPS64/edumips64/assets/200139/a01d73d5-1c80-4ceb-81dc-a3541dc5b64e)

**Comment by smallg0at** [comment]
It's likely that it's the problem of the language code of edumips64. I'll create a PR to change it into `zh_CN`.

**Comment by lupino3** [comment]
So, I fixed one thing: I pointed the newly created readthedocs project to the right conf file, and it now builds: https://edumips64-zn.readthedocs.io/zh_CN/latest/

However, it looks like the en/it versions don't detect the chinese version. But this looks solvable, and even if it doesn't work we can fix it by adding separate links to the different versions.

**Comment by smallg0at** [comment]
Readthedocs possibly think that it's a seperate one as its project slug is still `zn`. Maybe try removing it and restart from scratch?

**Comment by smallg0at** [comment]
@lupino3 and good news is that Chinese pdfs built by readthedocs behaves properly

**Comment by lupino3** [comment]
Great news! It means we *can* produce a working Chinese PDF.
Going to reset the project, let's see if it works.

**Comment by lupino3** [comment]
https://edumips64-zh-cn.readthedocs.io/zh_CN/latest/ retried with edumips64-zh_CN

**Comment by lupino3** [comment]
My bad. There was an extra configuration step to do in the main project that I had not done yet: marking the new project as a translation of the main one:

**Comment by lupino3** [comment]
Now it works! \o/
![image](https://github.com/EduMIPS64/edumips64/assets/200139/5b4f6185-c9fd-44c5-9559-2358f58fa4f4)
