### ISSUE TITLE
Implement dark mode in the UI

### ISSUE THREAD

**Issue by lupino3** [EduMIPS64/edumips64#796]
The Swing theme we are using has a dark mode: https://www.formdev.com/flatlaf/

We should enable a dark mode toggle somewhere in the UI, taking care of refreshing the look and feel after it is switched: https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html#dynamic

**Comment by smallg0at** [comment]
![image](https://github.com/EduMIPS64/edumips64/assets/30719670/791b6708-8c99-45e5-81e6-c77e580dbf0a)

![image](https://github.com/EduMIPS64/edumips64/assets/30719670/dd18d52a-550a-4eb5-b0c9-4545975f03dd)

Happened to be a dark mode enthusiast, working on this

**Comment by smallg0at** [comment]
![image](https://github.com/EduMIPS64/edumips64/assets/30719670/94d8be78-bfcc-4d7c-bbc3-2d2d03b56d93)

Icons have been redesigned!

**Comment by lupino3** [comment]
Web UI dark mode was implemented in #810.

**Comment by lupino3** [comment]
And the Swing UI dark mode was implemented in #802. Thanks @smallg0at for implementing both!
