### ISSUE TITLE
Create distribution packages

### ISSUE THREAD

**Issue by lupino3** [EduMIPS64/edumips64#8]
It would be nice to have packages for some of the major distributions (Debian/Ubuntu, Fedora). There is an already an unofficial package for Arch Linux at the address https://aur.archlinux.org/packages.php?ID=49802

**Comment by lupino3** [comment]
Maybe cross-distribution packages would be a good alternative here? For example, Canonical's [snap](https://snapcraft.io/store).

**Comment by pviotti** [comment]
I'm not really a fan of this sort of solution (shipping all dependencies into a single package, etc), but if you want to go that way you should also consider [AppImage](https://appimage.org/) and [Flatpak](https://flatpak.org/) ([here](https://askubuntu.com/a/1009061)'s a comparison) (and [here](https://xkcd.com/927/)'s the related xkcd).

**Comment by pviotti** [comment]
I've published an AUR package for Arch Linux: https://aur.archlinux.org/packages/edumips64/
Arch users can install it with a simple `yaourt -S edumips64` or using any other [AUR helper](https://wiki.archlinux.org/index.php/AUR_helpers).

Unfortunately the current `nodeps` package of version 1.2.5 does not include the docs folder, so the javahelp manual cannot be loaded. The non `-standalone` version produced by the current Gradle build fixes this. @lupino3 are you planning on releasing a new version using this build system anytime soon..?

**Comment by lupino3** [comment]
I hope I'll be able to do a release soon, ideally this weekend if everything goes as planned. Thanks for the package, I'll add it to the README together with the others.

**Comment by lupino3** [comment]
https://discourse.appimage.org/t/tutorial-to-create-appimage-out-of-java-application/461

**Comment by lupino3** [comment]
I had a look at Appimage and Snap, and one of the things I'd like is out-of-the-box Ubuntu support from CLI or store. 

Looks like Snap provides it, while Appimage is more like "download and run all-in-one" tool.

I'm having a look at creating a snap for now.

**Comment by lupino3** [comment]
To do:

- [x] allow use of preferences (already fixed in private branch)
- [ ] fix help
- [ ] fix splash screen
- [ ] try to reduce size by removing the gnome extension
- [ ] promote snap all the way to stable

**Comment by lupino3** [comment]
EduMIPS64 is now available from the Ubuntu App Store (Snap store): https://snapcraft.io/edumips64, installable via CLI with `snap install edumips64`.

This, plus native packages for Arch Linux and FreeBSD, is IMHO sufficient as good distribution for Linux (and FreeBSD!) desktop environments.
