### ISSUE TITLE
GUICycles.InstructionPanel have issue rendering when scrolled

### ISSUE THREAD

**Issue by smallg0at** [EduMIPS64/edumips64#801]
![image](https://github.com/EduMIPS64/edumips64/assets/30719670/547ec1ca-f32b-4920-9875-22068e08219a)

To reproduce: run any code, scroll up the cycles window with scroll wheel.

**Comment by lupino3** [comment]
Works for me on the latest code I have (work in progress code for #798).
I even tried to reproduce with the Simplified Chinese language.

Could you provide more info about your setup? OS, Window Manager (if Linux), etc.
Also, do you see the same problem with the latest official release JAR?

<img width="819" alt="image" src="https://github.com/EduMIPS64/edumips64/assets/200139/31ceb6b9-d872-4273-bae2-f1ac6856112d">

**Comment by smallg0at** [comment]
Problem do exist with official jar

![image](https://github.com/EduMIPS64/edumips64/assets/30719670/4dfaf657-1dae-42e7-8bd8-3f4904d7c7ec)


oh, and snap has this as well, although this package, fresh from GitHub actions, have zero zh_cn language support

![image](https://github.com/EduMIPS64/edumips64/assets/30719670/ca834af2-25a3-4c5b-8576-477d12ea3471)

**Comment by smallg0at** [comment]
@lupino3 weird, I don't experience this issue on a 1920*1280 (150%) RDP environment to the same pc as before

**Comment by lupino3** [comment]
I'm gonna mark this as impossible to replicate, unless we have a clear repro case. Thanks!
