### ISSUE TITLE
Build Snapcraft Action does not use correct source code

### ISSUE THREAD

**Issue by smallg0at** [EduMIPS64/edumips64#803]
Build Snapcraft Action does not use correct source code from the specific caller source (e.g. Pull Request), but will use master branch instead. This makes the action basically useless for testing purposes.

**Comment by lupino3** [comment]
I can't check now, but I suspect something changed with recent versions of the `checkout` Github action. The behavior I am seeing while testing the Web UI in #798 would be explained by the Github action building and deploying `master` rather than the PR code.

**Comment by lupino3** [comment]
Do you have a log of this happening? What PR and what build run?

**Comment by smallg0at** [comment]
> Do you have a log of this happening? What PR and what build run?

like #802, all CI builds have this issue

**Comment by smallg0at** [comment]
Came up with a promising fix, but needs to wait 10 minutes till it build...

**Comment by lupino3** [comment]
Yes, you are absolutely right. The `snapcraft` config will clone the repo as it is now:

https://github.com/EduMIPS64/edumips64/blob/897f559ebda971760aae0bcad949b3cf38847b02/snapcraft.yaml#L13

https://snapcraft.io/docs/snapcraft-parts-metadata#heading--source

**Comment by lupino3** [comment]
We can try using `source: .` to build without fetching new code

**Comment by lupino3** [comment]
@smallg0at I cannot test `snap` packages right now, but please let me know if #805 fixes it for you. Based on my understanding of the code, it should work now.
