### ISSUE TITLE
First instruction missing from Cycles window when reset after execution terminates

### ISSUE THREAD

**Issue by Wenke-D** [EduMIPS64/edumips64#875]
Version: 1.2.9
java 11.0.11 2021-04-20 LTS

**what happened**
after running a program, if we click the reset button, in the cycle window, the IF stage of the first instruction of this program will not be displayed.

**how to fix**
I need to reopen the same file to get the correct display.

I put screenshots here.

**first time open the file**
![first_open](https://github.com/EduMIPS64/edumips64/assets/65447561/c2ae6730-c919-4c6a-90d3-35481ce7096c)

**run(F4) the program**
![after_run](https://github.com/EduMIPS64/edumips64/assets/65447561/08620057-99b9-460c-8999-4681ffcedd90)

**click reset**
![after_click_reset](https://github.com/EduMIPS64/edumips64/assets/65447561/2c4e4e70-d092-4d4d-88d7-0f9ec6d5c81c)

**reopen the file**
![reopen_the_file](https://github.com/EduMIPS64/edumips64/assets/65447561/1f28395d-14c4-4644-8050-11ad06b6c6af)

**Comment by lupino3** [comment]
Verified that this bug is also present in version 1.3.0, and only affects the Swing UI, not the web UI. 

Thanks for the bug report!

**Comment by lupino3** [comment]
As a work-around, it looks like if you reload again you will see the first instruction correctly.
